[package]
name = "mocra"
version = "0.1.0"
edition = "2024"
description = "Unified crate that re-exports mocra workspace crates"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.ouiex.dev/eason/mocra"

[workspace]
resolver = "3"
members = ["cacheable","common", "downloader", "engine", "errors", "proxy", "queue", "scheduler", "sync", "tests", "utils","js-v8"]

[workspace.dependencies]
async-trait = "0.1"
reqwest = { version = "0.13", features = ["default","brotli","form", "cookies", "json", "socks", "gzip", "deflate", "zstd"] }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
toml = "0.9"
uuid = { version = "1", features = ["serde", "v7","zerocopy"] }
url = "2"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
deadpool-redis = { version = "0.22", features = ["json", "script", "serde","streams"] }
sea-orm = { version = "1", features = ["postgres-array", "runtime-tokio-native-tls", "sqlx-postgres"] }
rdkafka = { version = "0.38", features = ["cmake-build"] }
futures = "0.3"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.11"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
tracing-log = "0.2"
once_cell = "1"
reqwest_cookie_store = { version = "0.9", features = ["serde"] }
v8 = "142"
time = { version = "0.3", features = ["local-offset", "formatting", "parsing"] }
polars = { version = "0.52.0", features = ["json", "lazy", "serde", "csv", "timezones", "strings", "ipc", "dtype-decimal"] }
polars-ops = { version = "0.52.0", features = ["pivot"] }
chrono-tz = "0.10"
bytes = { version = "1", features = ["serde"] }
calamine = { version = "0.32.0", features = ["chrono", "dates"] }
libloading = "0.9.0"
semver = { version = "1", features = ["serde"] }
dyn-clone = { version = "1" }
base64 = { version = "0.22" }
ring = { version = "0.17" }
md5 = "0.8"
regex = { version = "1" }
urlencoding = "2"
axum = { version = "0.8", features = ["json"] }
dashmap = "6"
futures-util = "0.3"
tokio-tungstenite = { version = "0.28", features = ["native-tls"] }
common = { path = "common" }
downloader = { path = "downloader" }
engine = { path = "engine" }
queue = { path = "queue" }
scheduler = { path = "scheduler" }
sync = { path = "sync" }
utils = { path = "utils" }
proxy = { path = "proxy" }
errors = { path = "errors" }
cacheable = { path = "cacheable" }
js-v8 = { path = "js-v8" }

[dependencies]
common.workspace = true
downloader.workspace = true
engine.workspace = true
queue.workspace = true
scheduler.workspace = true
sync.workspace = true
utils.workspace = true
proxy.workspace = true
errors.workspace = true
cacheable.workspace = true
js-v8 = { workspace = true, optional = true }

[features]
default = []
js-v8 = ["dep:js-v8"]

[lib]
name = "mocra"
path = "src/lib.rs"
